# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test

      # Deploy to GitHub Pages on push to main branch
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports/html/.jsons
          publish_branch: gh-pages
          dest_dir: reports/main
          keep_files: true

      # Upload test report as artifact on pull requests
      - name: Upload PR Report
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: reports/html/.jsons/mochawesome.json
